project:
  type: website
  output-dir: docs

website:
  title: "Macroeconomics 2 Presentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        href: https://paulogcd.github.io

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



