project:
  type: website
  output-dir: docs

website:
  title: "Macroeconomics 2 Presentation"
  navbar:
    title: false
    background: '#e0e0e0'
    left:
      - href: ../
        text: Home
      - href: index.qmd
        text: Our presentation
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/Paulogcd/Macroeconomics-2-Presentation
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



